name: biobb_wf_pmx_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_common==3.0.1
  - biobb_pmx==3.0.2
  - biobb_md==3.0.1
  - biobb_analysis==3.0.2
  - nb_conda_kernels
  - nbconvert==5.6.1
  - plotly
  - conda