name: biobb_wf_pmx_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_pmx==4.1.0
  - biobb_gromacs==4.1.0
  - biobb_analysis==4.1.0
  - jupyter_client==7.3.2
  - traitlets==5.9.0
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - plotly
  - conda
