name: biobb_wf_pmx_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_pmx==3.6.0
  - biobb_md==3.6.0
  - biobb_analysis==3.6.0
  - nbconvert==5.6.1
  - nb_conda_kernels
  - ipywidgets
  - plotly
  - conda