name: biobb_wf_pmx_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.6
  - biobb_common==1.1.6
  - biobb_pmx==1.0.0
  - biobb_md==1.1.7
  - biobb_analysis==1.0.8
  - plotly
  - conda