name: biobb_wf_pmx_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.6
  - biobb_common==2.0.1
  - biobb_pmx==2.0.2
  - biobb_md==2.0.0
  - biobb_analysis==2.0.1
  - plotly
  - conda