name: biobb_wf_pmx_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_pmx==3.5.0
  - biobb_md==3.5.1
  - biobb_analysis==3.5.0
  - nbconvert==5.6.1
  - ipywidgets
  - plotly
  - conda