name: biobb_wf_pmx_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_pmx==3.8.1
  - biobb_gromacs==3.8.0
  - biobb_analysis==3.8.0
  - ipywidgets==7.6.6
  - jupyter_contrib_nbextensions
  - plotly
  - conda